mybatis:
  type-aliases-package: com.aladdin.entity
#  mapper-locations: classpath:/com/aladdin/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
spring:
  main:
    banner-mode: off
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/scaffold?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=true&allowMultiQueries=true
    username: root
    password: Chang0.com
mapper:
  mappers:
    - com.aladdin.core.CoreMapper
  not-empty: false
  identity: MYSQL
